spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  webflux:
    base-path: /personvern/kodeverk
  kafka:
    consumer:
      group-id: consumer-personvern-kodeverk # consumer-utdanning-vurdering-<your-instance-id>

fint:
  security:
    org-id: false
  consumer:
    org-id:
    domain: personvern
    package: kodeverk
  kafka:
    application-id: consumer-personvern-kodeverk
    enable-ssl: true
    topic:
      org-id:
      domain-context: fint-core
  relations:
    default-base-url: https://beta.felleskomponent.no

logging:
  level:
    root: debug
    org.apache.kafka: WARN
    org:
      springframework:
        security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus